name = "Craftoria"
author = "TeamAOE"
version = "1.31.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "313f5edb6a3b80a8e753217d05f3c5d25bfd32a9a23a8831033f0ccd429911cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
