name = "Craftoria"
author = "TeamAOE"
version = "1.31.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15d88f539406e4fe6e14ab569f364e53d44b6e75c8e794211ea9ca9ebfabf45e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
