name = "Craftoria"
author = "TeamAOE"
version = "1.32.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e1b5f1c4d17109b871be2f752d2f0940429e52a72f8661b767e736e97014a18"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
